name: CI

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: debian-latest
    steps:
      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Installer les dépendances
        run: pip install -r requirements.txt
      - name: Lancer les tests
        run: pytest
